# Configuración de la aplicación para Fly.io
app = 'api-vanesa-bodeguita'
primary_region = 'mia'  # Miami - más cerca de Latinoamérica

[build]

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '5s'
    method = 'GET'
    path = '/health'

[vm]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[[vm.env]]
  FIREBASE_PROJECT_ID = 'negociovanesa'
